kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "content.fullname" . }}
  labels:
    {{- include "content.labels" . | nindent 4 }}
data:
  MYSQL_HOST: "{{ .Values.mysql_host }}"
  MYSQL_DATABASE: "{{ .Values.mysql_database }}"